### ISSUE TITLE
このサイトについてページ作成

### ISSUE THREAD

**Issue by ak2ie** [spendingjp/openspending-frontend#10]
「このサイトについて」のページを作成する

 - [現行ページ](https://tsukubashi.spending.jp/about.html)

# タスク
- [ ] 所得控除額や課税対象額は埋め込み or 共通設定? から取得するかを検討
- [ ] 予算配分比率の基準日もどこから取得するか検討
- [ ] サイトは再々構築するので、経緯のところの日付を再確認

**Comment by kaizumaki** [comment]
別issueに切ったので、こちらは一旦クローズとします。
