### ISSUE TITLE
データの出所ページの作成

### ISSUE THREAD

**Issue by ak2ie** [spendingjp/openspending-frontend#11]
サイトで使用しているデータの出所を表示するページを作成する

 - [現行ページ](https://tsukubashi.spending.jp/sources.html)

# タスク
- [x] データの基準年度の取得方法を検討（埋め込み or 共通設定から取得?）
- [ ] 所得控除額や課税対象所得額の取得方法を検討（埋め込み or 共通設定から取得?）
- [ ] 「私のデータの視覚化をお願いできますか？」の内容は、専用システムを作成するので変更する

**Comment by kaizumaki** [comment]
別issueに切ったので、こちらは一旦クローズとします。
