### ISSUE TITLE
データの出所ページ「どのように、可視化に使っているデータの分類を決めているのか？」作成

### ISSUE THREAD

**Issue by ak2ie** [spendingjp/openspending-frontend#23]
データの出所ページ「どのように、可視化に使っているデータの分類を決めているのか？」について、次期版サイトに合わせた内容を作成する。

現行版は以下の内容。

> このサイトは、令和２年度の自治体の一般会計当初予算の事業名単位のデータをもとに、各事業が国連のClassification of Functions of Government (COFOG)の第２レイヤー分類のどこに紐づくかを一つ一つ判断して作成しています。

**Comment by kaizumaki** [comment]
別issueに切ったので、こちらは一旦クローズとします。
