### ISSUE TITLE
データの出所ページ「私のデータの視覚化をお願いできますか？」作成

### ISSUE THREAD

**Issue by ak2ie** [spendingjp/openspending-frontend#24]
データの出所ページ「私のデータの視覚化をお願いできますか？」について、次期版サイトに合わせた内容を作成する。

現行版は以下の内容。

> はい、できます。もし、視覚化したいデータをお持ちであれば、COFOGフォーマットに紐付けしたデータセット（Excel）をお問合せにお送りください。

**Comment by kaizumaki** [comment]
別issueに切ったので、こちらは一旦クローズとします。
